### ISSUE TITLE
mjml2: Render and redirect the result to a file

### ISSUE THREAD

**Issue by Bloggerschmidt** [mjmlio/mjml#209]
If I want to render the result to a file with

`mjml input.mjml -o my-email.html`

it behaves like the output to terminal

`mjml input.mjml`

Working with mjml 2 and node 4.4.3
Maybe a bug? Any workarround?

**Comment by francoismart** [comment]
+1
In my case, i don't have any error on screen with command line and the file is not generated
 
If i use the watch option I have :

/home/vagrant/.node_modules_global/lib/node_modules/mjml/node_modules/mjml-cli/lib/client.js:106
  bufferPromise.then(function (mjml) {
                ^

TypeError: bufferPromise.then is not a function
    at render (/home/vagrant/.node_modules_global/lib/node_modules/mjml/node_modules/mjml-cli/lib/client.js:106:17)
    at StatWatcher.<anonymous> (/home/vagrant/.node_modules_global/lib/node_modules/mjml/node_modules/mjml-cli/lib/client.js:162:12)
    at emitTwo (events.js:100:13)
    at StatWatcher.emit (events.js:185:7)
    at StatWatcher._handle.onchange (fs.js:1369:10)

Only solution is to get the output on console ....
thanks in adance for your help

**Comment by iRyusa** [comment]
@francoismart it looks like you have a node version issue, can you give me your node version using `node -v` ?

@Bloggerschmidt I'll take a look, thanks for reporting it !

**Comment by Bloggerschmidt** [comment]
@iRyusa Thank you for your great work. I find out, that 
`mjml -r input.mjml -o my-email.html`
works. So, this issue is about the `-r`

**Comment by francoismart** [comment]
@iRyusa i get 5.6.0 so i'm going to upgrade to 6  ?
another solution would be the desktop app isn't it ?

**Comment by iRyusa** [comment]
@francoismart I was mislead by the error, @GuillaumeBadi has opened a PR #206 it should fix the watch option sorry about that !

**Comment by francoismart** [comment]
@iRyusa  nice. but my first issue is to have a log on screen or file when nothing is generated .... is there a way to see errors ? thanks in advance

**Comment by iRyusa** [comment]
@francoismart can you share your mjml ? thanks

**Comment by pixelize** [comment]
@iRyusa Got the exact same error "TypeError: bufferPromise.then is not a function"
as @francoismart since update 2.0 when compiling with the -w option, any help ?

**Comment by GuillaumeBadi** [comment]
@pixelize this is fixed by the latest pull request, it will be updated soon on npm

**Comment by pixelize** [comment]
Thanks, awesome work guys ;) If anyone would be kind to have a look to my problem : 
https://github.com/mjmlio/mjml/issues/204

Thanks in advance ;)

**Comment by francoismart** [comment]
@iRyusa done on slack ... thank you and waiting for th update

**Comment by iRyusa** [comment]
Hi !
It should be ok now on `2.0.1` ! I close it, you can re-open if needed
