### ISSUE TITLE
@babel/runtime dep missing for top-level mjml package

### ISSUE THREAD

**Issue by jnardone** [mjmlio/mjml#1905]
**Describe the bug**

(this is a regression from 4.6.2)

In 4.6.3 the npm module lib/index.js for `mjml` contains

```
var _interopRequireWildcard = require("@babel/runtime/helpers/interopRequireWildcard");
```

however, @babel/runtime is not a dependency for `mjml` (it is for its other projects like mjml-accordian)

This means that when you install without an explicit @babel/runtime in your package.json, a require of mjml produces

```
Uncaught Error: Cannot find module '@babel/runtime/helpers/interopRequireWildcard'
Require stack:
- /app/node_modules/mjml/lib/index.js
- <repl>
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/node_modules/mjml/lib/index.js', '<repl>' ]
}
```

Can we add this to the main `mjml` package as a dependency?

**MJML environment (please complete the following information):**
 - OS: MacOS, linux
 - MJML Version 4.5.3

**Comment by iRyusa** [comment]
Well every package of MJML has it listed in dep so it should install it anyway ?
But for consistency let's add it to actual package yep

**Comment by jnardone** [comment]
for us it doesn't work/doesn't get promoted up.  It's in the node_modules directories of the component packages but not visible to the top-level package.

Prior to 4.6.3 there wasn't a direct reference to the runtime in the top-level package.

**Comment by iRyusa** [comment]
Yup 4.6.X has migrated from babel 6 to 7, so it might be why you get that. Can you try to clean your node modules first, as node modules is flatten for a while now ?

**Comment by jnardone** [comment]
I did try that.  It made no difference.  But the fact that the main mjml module now has a direct reference in code to @babel/runtime means it should include that as a dependency.

node v12.16.3
npm 6.14.4

**Comment by jnardone** [comment]
(by the way, this is a great library and really helped us solve our email templating problems in a really great way.)

**Comment by iRyusa** [comment]
> But for consistency let's add it to actual package yep
We'll add it for next release as I've said.

Can you do a `ls -l` inside your node modules ? I just tried a clean install and everything works out of the box here 🤔

**Comment by jnardone** [comment]
It's really large.  (860 lines) so I'm not going to paste that in.  We don't even have a @babel dir in node_modules for our server-side app.  

Note that the fact that it works for you is due to somewhat indeterministic behavior of npm, and it logic about promoting modules up the top level is not guaranteed.  

For now we've rolled back to 4.6.2 and could, if we had to, include @babel/runtime as a specific dependency of OUR app, but really the only fix is to explicitly declare it at the top level for mjml.

**Comment by iRyusa** [comment]
Ok then it's maybe an issue with your lockfile I guess... 

> Note that the fact that it works for you is due to somewhat indeterministic behavior of npm, and it logic about promoting modules up the top level is not guaranteed.

Whole dependency tree is now flattened out (since npm 3?), so it's not really an indeterministic behavior. There's no way any other modules would successfully require it if it's not in your `node_modules` so you have an install issue at first.

**Comment by jnardone** [comment]
Just a bump that this is still a real issue with real package.json/package-lock.json.  The dependencies for babel-runtime do not always get hoisted up to the top level depending on other dependencies in the graph, so without an explicit declaration of babel-runtime (in the top level mjml package, which now explicitly calls a babel-runtime function) this fails.

**Comment by iRyusa** [comment]
As said this is not a critical thing as any standard npm/yarn install will catch the package as a dep from any mjml package. I still have 0 idea how your package lock doesn't list it, or how you can reproduce this behavior in a clean project. If it's the case feel free provide a repository to reproduce.

We're working on 4.7 features first, and it will be released with it.

**Comment by zygimantas** [comment]
After updating to 4.7 I started getting `EXEC : error : Cannot find module '@babel/runtime/helpers/createSuper'`

**Comment by iRyusa** [comment]
Can you provide more informations like node version, did you tried a clean install ...

**Comment by zygimantas** [comment]
@iRyusa thanks! I forgot about clean install. After removing node_modules and package.lock.json, it works as expected.
```
node -v
v14.4.0
npm -v
6.14.4
```

**Comment by doits** [comment]
yarn v2 complains about it, too:

```
# yarn run mjml

Error: mjml tried to access @babel/runtime, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

👍 for adding it as a dependency directly

**Comment by doits** [comment]
I opened #2093 to hopefully fix this
